Learning about Numpy


In [2]:
import numpy as np

In [3]:
print("Learning Numpy")

Learning Numpy


Basics

In [4]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
#Get Dimension

print(a.ndim)
print(b.ndim)

1
2


In [7]:
#Get Shape

print(a.shape)
print(b.shape) #2 rows, 3 columns

#Get Type

print(a.dtype)
print(b.dtype)

#Get Size

print(a.itemsize)
print(b.itemsize)

#Get Total Size

print(a.size)
print(b.size)

(3,)
(2, 3)
int64
float64
8
8
3
6


Accessing/Chaning specific elements,rows,coloumns, etc

In [8]:
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14],[15, 16, 17, 18, 19, 20, 21]])
print(c) 

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


In [9]:
a.shape

(3,)

In [12]:
#Get a specific element [row, column]

print(c[1, 6])

14


In [13]:
#Get a specific row

print(c[0, :])

[1 2 3 4 5 6 7]


In [14]:
#Get a specific column

print(c[:, 2])

[ 3 10 17]


In [15]:
#Getting a little more fancy [startindex:endindex:stepsize]

print(c[0, 1:6:2])  #start at index 1 and go up to index 6, step size of 2

[2 4 6]


In [18]:
#Change an element

c[1, 5] = 69
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 69 14]
 [15 16 17 18 19 20 21]]


In [23]:
#Change a column

c[:, 2] = [1, 2, 3]
print(c)

#3D Example

print("3D Example")

d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(d)


[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 69 14]
 [15 16  3 18 19 20 21]]
3D Example
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Iniatilzing diff types of Arrays


In [25]:
e = np.zeros(5)

print(e)

f= np.zeros((2, 3))
print(f)


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [28]:
np.full((3, 3), 59)



array([[59, 59, 59],
       [59, 59, 59],
       [59, 59, 59]])

In [29]:
np.full_like(f, 4)  #Create an array like f, but fill it with 4s

array([[4., 4., 4.],
       [4., 4., 4.]])

In [30]:
#Random decimal numbers

np.random.rand(4, 2)

array([[0.13930524, 0.88801201],
       [0.08563232, 0.96999138],
       [0.41701797, 0.89898163],
       [0.56792019, 0.24550933]])

In [45]:
np.random.randint(70, size=(3, 3))  #Random integers from 0 to 7

array([[21, 60,  2],
       [64,  3, 56],
       [16, 34, 51]], dtype=int32)

In [46]:
np.identity(5)  #Create an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)

print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [58]:
output = np.ones((5, 5))
print(output)

print("Z will be:")

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

print("Output will be:")

output[1:4, 1:4] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Z will be:
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
Output will be:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Mathmatics/Arithmetics Operations


In [64]:
z = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(z + y)
print(z - y)
print(z * y)
print(z / y)
print(z**2 + y)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[ 5  9 15]
[1 2 3]


In [65]:
new = z - 2
print(new)

[-1  0  1]


Trignometry


In [68]:
#Take the sin of all the values in the array

print(np.sin(z))


u = np.ones((2, 3))
print(np.tan(u))

[0.84147098 0.90929743 0.14112001]
[[1.55740772 1.55740772 1.55740772]
 [1.55740772 1.55740772 1.55740772]]


Linear Algebra

In [72]:
a = np.array([1, 2, 3, 4])
print(a)

print(a + 1)

b = np.ones((3,2)) + 1  #(row, column)
print(b)

[1 2 3 4]
[2 3 4 5]
[[2. 2.]
 [2. 2.]
 [2. 2.]]


In [85]:

#Statistics

stats = np.array([[1, 2, 3], [4, 5, 6]])

print(np.min(stats))
print(np.max(stats))
print(np.sum(stats, axis=0))  #Sum of columns
print(np.sum(stats, axis=1))  #Sum of rows

#Reorganizing Arrays

before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((8, 1))
print(after)



1
6
[5 7 9]
[ 6 15]
[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [88]:

#Vertically stacking vectors

v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

#Horizontal stack

h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:

#Load data from file

filedata = np.genfromtxt('data.csv', delimiter=',') #delimiter is the separator in the file meaning the data is separated by commas
filedata = filedata.astype('int32')
print(filedata)



ValueError: Some errors were detected !
    Line #2 (got 1 columns instead of 9)
    Line #3 (got 1 columns instead of 9)
    Line #4 (got 1 columns instead of 9)
    Line #6 (got 1 columns instead of 9)
    Line #7 (got 3 columns instead of 9)
    Line #8 (got 2 columns instead of 9)
    Line #9 (got 2 columns instead of 9)
    Line #10 (got 1 columns instead of 9)
    Line #11 (got 1 columns instead of 9)
    Line #12 (got 1 columns instead of 9)
    Line #13 (got 1 columns instead of 9)
    Line #14 (got 1 columns instead of 9)
    Line #15 (got 2 columns instead of 9)
    Line #17 (got 1 columns instead of 9)
    Line #18 (got 2 columns instead of 9)
    Line #19 (got 1 columns instead of 9)
    Line #20 (got 1 columns instead of 9)
    Line #21 (got 1 columns instead of 9)
    Line #22 (got 1 columns instead of 9)
    Line #25 (got 1 columns instead of 9)
    Line #28 (got 1 columns instead of 9)
    Line #29 (got 1 columns instead of 9)
    Line #31 (got 1 columns instead of 9)
    Line #34 (got 6 columns instead of 9)
    Line #37 (got 1 columns instead of 9)
    Line #38 (got 1 columns instead of 9)
    Line #41 (got 1 columns instead of 9)
    Line #42 (got 5 columns instead of 9)
    Line #43 (got 1 columns instead of 9)
    Line #46 (got 1 columns instead of 9)
    Line #47 (got 1 columns instead of 9)
    Line #48 (got 1 columns instead of 9)
    Line #50 (got 4 columns instead of 9)

In [ ]:
#Boolean Masking and Advanced Indexing

filedata > 50

filedata[filedata > 50]

np.any(filedata > 50, axis=0)

((filedata > 50) & (filedata < 100))

(~((filedata > 50) & (filedata < 100)))

np.all(filedata > 50, axis=0)

((filedata > 50) & (filedata < 100))

print(filedata[(filedata > 50) & (filedata < 100)])


#the following code snippet will print the values in the first column of the filedata array, where the values in the second column are greater than 50

